update version number

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -16,8 +16,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        # numpy 3.12 is not available yet
-        python-version: ["3.8", "3.9", "3.10", "3.11"]
+        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
 
     steps:
     - uses: actions/checkout@v3
@@ -33,17 +32,31 @@ jobs:
         restore-keys: |
           ${{ runner.os }}-pip-${{ matrix.python-version }}-
           ${{ runner.os }}-pip-
-    - name: Install dependencies
+    - name: Install Dependencies with Retry
       run: |
         cp packaging/setup.py .
-        pip install .
+        max_attempts=5
+        sleep_seconds=10
+        attempt_num=1
+        until timeout $sleep_seconds pip install . || [[ $attempt_num -eq $max_attempts ]]
+        do
+          echo "Attempt $attempt_num of $max_attempts failed! Trying again in $sleep_seconds seconds..."
+          sleep $sleep_seconds
+          ((attempt_num++))
+        done
+
+        if [[ $attempt_num -eq $max_attempts ]]; then
+          echo "All $max_attempts attempts have failed!"
+          exit 1
+        fi
+    - name: Install Test Dependencies
+      run: |
         python tests/smoke_test.py
         python -m pip install --upgrade pip
         pip install --no-deps -r tests/requirements.lock
         pip install .
     - name: Run Tests
       env:
-        COVERAGE: false
         CI: true
       run: |
         python -m unittest discover tests -v
@@ -54,7 +67,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        python-version: ["3.10"]
+        python-version: ["3.12"]
 
     steps:
     - uses: actions/checkout@v3
@@ -73,7 +86,6 @@ jobs:
     - name: Coverage
       env:
         COVERAGE: true
-        CI: true
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
       run: |
         python -m pip install --upgrade pip
